services:
    Sidus\AdminBundle\Twig\AdminExtension:
        autowire: true
        public: false
        tags:
            - twig.extension

    Sidus\AdminBundle\Templating\TemplateResolver:
        autowire: true
        public: false

    Sidus\AdminBundle\Templating\TemplateResolverInterface:
        alias: Sidus\AdminBundle\Templating\TemplateResolver
